# Generated by Django 4.1.2 on 2023-03-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spritleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Multiple', models.IntegerField()),
                ('Plus', models.IntegerField()),
                ('Minus', models.IntegerField()),
                ('Divide', models.IntegerField()),
            ],
        ),
    ]
